### ISSUE TITLE
Is it impossible to use with stack 2?

### ISSUE THREAD

**Issue by bewakes** [Tehnix/miso-isomorphic-stack#7]
I tried running this and it failed saying `GHCJS is no longer supported by Stack`. Turns out stack-2 does not support ghcjs.

Does this mean I can't use this with stack 2?

**Comment by Tehnix** [comment]
Unfortunately, since stack dropped support for GHCJS, this repo is no longer that useful. 

As far as I know, stack also has no intention of adding support for it again, and I'd recommend biting the bullet and using Nix if you're gonna be working with GHJCS :(

You're probably aware of this already, but https://github.com/FPtje/miso-isomorphic-example is a Nix version of this :)

**Comment by bewakes** [comment]
That's kind of sad. The issue with nix for me is that it's difficult to set up editor tooling(for nvim in particular).
thanks anyways!

**Comment by Tehnix** [comment]
@bewakes yeah :/ that was also the main driver behind this repo, since I found the stack experience to be a lot nicer. Hopefully when one of the WASM GHC's (Asterius or webGHC) lands it'll also be with nicer tooling 😅

**Comment by bewakes** [comment]
Let's hope so. :D
